DECLARE
CURSOR CUR_EMPLEADO  IS SELECT * FROM empleado_ventas;
CURSOR CUR_SUCURSAL  IS SELECT * FROM sucursal;

BEGIN
FOR REC_EMP IN CUR_EMPLEADO LOOP
FOR REC_SUC IN CUR_SUCURSAL LOOP

IF REC_SUC.id_cliente=REC_EMP.id_cliente THEN

DBMS_OUTPUT.PUT_LINE('NOMBRE: ' || REC_EMP.NOMBRE_CLIENTE || ' SUCURSAL: ' || REC_SUC.NOMBRE);

END IF;
END LOOP;
END LOOP;

END;
/
